<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>SELER</title>
</head>
<body>
    <img src="https://www.polskasmakuje.pl/wp-content/uploads/2019/04/seler.jpg" alt="A jumping Beaver" >
    <br>
    <img src="" alt="A cool looking Beaver with sunglasses" width="80">
    <br>
    <img src="https://www.supernasiona.pl/img/1192/.jpg" alt="A happy Beaver" width="20%">
</body>
</html>
